### ISSUE TITLE
Poročilo in uvoz

### ISSUE THREAD

**Issue by jaanos** [katarinabrilej/APPR-2017-18#2]
Poročila ti trenutno ne prevede - prvi problem se pojavi v programu `uvozi.zemljevid.r`:

https://github.com/katarinabrilej/APPR-2017-18/blob/38aa5d494848617629134d58ea28c6e6f459966b/lib/uvozi.zemljevid.r#L61-L63

To je bilo podano kot primer, zato zakomentiraj vrstico 63 (kakor je to že bilo).

Naslednji problem se pojavi v programu `uvoz.r`, ko se sklicuješ na neobstoječo spremenljivko `krim`:

https://github.com/katarinabrilej/APPR-2017-18/blob/38aa5d494848617629134d58ea28c6e6f459966b/uvoz/uvoz.r#L59-L62

Verjetno si tukaj hotela uporabiti `obs`. Sicer pa lahko, glede na to, da je šlo le za preverjanje, te vrstice zakomentiraš ali pobrišeš.

Naslednja težava se pojavi v funkciji `stevilo_zaprtih` - iz Wikipedije bo treba uvoziti prvo tabelo na strani, ne druge (morda se je stran v vmesnem času spremenila).

Opažam še, da v `vizualizacija.r` pretvarjaš stolpce v števila po filtriranju. To raje stori že pri uvozu, torej v funkcijah `uvozi.brezposelnost2`, `uvozi.obsojeni_po_obcinah` in `uvozi.obsojeni_po_obcinah2` (pa morda še kje), npr.
```R
data$`stevilo obsojenih` <- parse_number(data$`stevilo obsojenih`)
```
Sicer pa odsvetujem uporabo presledkov (pa tudi šumnikov in drugih posebnih znakov) v imenih stolpcev - zaradi presledka je bilo potrebno v zgornjem primeru okoli imena stolpca postaviti \`\`.

Vidim, da na `graf3` prikazuješ stopnjo brezposelnosti in število obsojenih na istem grafu. Ali gre tukaj za isto lestvico (tj., delež prebivalstva)? Če je tako, bi bilo smiselno že pri združevanju podatkov to storiti po vrsticah, da bo razpredelnica v obliki *tidy data*, npr.:
```R
brezposelnost_in_obsojeni <- rbind(brezposelnost2 %>% transmute(leto, obcina,
                                                                meritev = "brezposelni",
                                                                stopnja = stopnja_brezposelnosti),
                                   obsojeni_po_obcinah2 %>% transmute(leto, obcina,
                                                                      meritev = "obsojeni",
                                                                      stopnja = stevilo_obsojenih))
```
Tako tudi ne bo potrebna uporaba `melt` v `vizualizacija.r`. Če pa ne gre za isto skalo, pa podatka raje prikaži na dveh grafih, saj zna to biti zavajajoče (je pa v tem primeru trenutni način združevanja v redu).

Še to: v `vizualizacija.r` ne izrisuj grafov in zemljevidov - to stori v poročilu z blokom kode na mestu, kjer želiš graf oziroma zemljevid prikazati. V poročilu tudi pazi, da so bloki kode ustrezno razmejeni - trenutno imaš zakomentirano vrstico \`\`\`, ki bi morala konćati blok kode, kjer se kliče `vizualizacija.r`. Zato se sivo ozadje nadaljuje tudi v vrstico `***`, ki več ni del kode (pač pa v RMarkdownu izriše vodoravno črto), in bi tako sprožila napako.

**Comment by katarinabrilej** [comment]
Hvala za popravke. Zdi se mi, da sem vse popravila, vendar pa se mi poročilo še vedno noče prevesti, saj dobim opozorilo v vrstici 81: object "graf1" not found ....

**Comment by jaanos** [comment]
Meni je prevedlo, tako da bom dodal povezavo na zadnji commit. Če boš še kaj spreminjala in boš želela posodobiti povezavo, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-zagovori) (glej navodila spodaj).

Še to: pri prvem grafu imaš imena držav v legendi, hkrati pa še v oznakah osi x, kjer se pa prekrivajo. Zato svetujem, da jih tam odstraniš - grafu prištej še `theme(axis.text.x = element_blank())`.
