### ISSUE TITLE
zemljevid občin

### ISSUE THREAD

**Issue by katarinabrilej** [katarinabrilej/APPR-2017-18#3]
Pozdravljeni,

uvozila sem zemljevid slovenskih občin, vendar pa je skoraj polovica zemljevida obarvanega sivo (občin v zemljevidu je namreč veliko premalo, saj je velikokrat namesto imena napisan NA) in ne vem kako bi to popravila.

del kode:

obcine <- uvozi.zemljevid("http://biogeo.ucdavis.edu/data/gadm2.8/shp/SVN_adm_shp.zip", 
                          "SVN_adm2",encoding = "Windows-1250") %>% pretvori.zemljevid()

obcine$NAME_2 <- as.character(obcine$NAME_2)
obsojeni_po_obcinah2$obcina <- as.character(obsojeni_po_obcinah2$obcina)
zemljevid.obsojeni <- ggplot() +
  geom_polygon(data = obsojeni_po_obcinah2 %>% filter(leto == "2016") %>% right_join(obcine, by = c("obcina" = "NAME_2")),
               aes(x = long, y = lat, group = group, fill = obsojeni), color = "black")+
  xlab("") + ylab("") + ggtitle("Stopnja obsojenih po slovenskih obcinah")

**Comment by jaanos** [comment]
Da ti bo zemljevid pravilno uvozilo, pri `uvozi.zemljevid` uporabi parameter `encoding = "UTF-8"`.

Sicer pa izgleda, da je ta zemljevid nekoliko zastarel, saj je v njem le 192 občin, poleg tega pa nekateri šumniki manjkajo. Svetujem, da raje uvoziš zemljevid, ki smo ga uporabljali na vajah:
```R
obcine <- uvozi.zemljevid("http://baza.fmf.uni-lj.si/OB.zip",
                          "OB/OB", encoding = "Windows-1250") %>%
  pretvori.zemljevid()
```
Imena občin bodo v stolpcu `OB_UIME` - vseeno pa preveri, ali se imena ujemajo, ter jih po potrebo popravi bodisi v podatkih ali pa v zemljevidu.

**Comment by katarinabrilej** [comment]
sem uvozila zemljevid tako kot na vajah in popravila recimo ime za občino Ankaran, tako da mi to zdaj obarva, vendar pa mi še vedno vse občine, ki vsebujejo šumnike obarva sivo.
S šumniki imam recimo probleme že pri uvozu tabel, kjer se mi prikažejo kot Ajdov<U+0161><U+010D>ina namesto Ajdovščina, vendar pa se v primeru ko narišem graf imena spet prav izpišejo

**Comment by jaanos** [comment]
Če se na grafih (oz. kjerkoli v poročilu) imena pravilno izpišejo, potem bo tako v redu. Kako se ti pa izpišejo šumniki, če po uvozu zemljevida narediš `levels(obcine$OB_UIME)`?

**Comment by katarinabrilej** [comment]
če naredim levels(obcine$OB_UIME) dobim samo 133 občin, vse tiste s šumniki pa izginejo

**Comment by jaanos** [comment]
Morda lahko poskusiš pri `uvozi.zemljevid` uporabiti parameter `encoding = ""`. Šumniki sicer najbrž še vedno ne bodo delovali, a bi vsaj vse občine morale ostati v zemljevidu.

Če imaš čas, se lahko zglasiš s svojim računalnikom jutri ob 10h ali ob 12h v kabinetu 5.14, pa bova pogledala, kako bi lahko to rešila (prosim povej, kdaj bi prišla).

**Comment by katarinabrilej** [comment]
Tudi če uporabim  encoding = "" je pri levels(obcine$OB_UIME) spet samo 133 občin.
Bom prišla jutri ob 12ih.

**Comment by jaanos** [comment]
V redu, velja.

**Comment by katarinabrilej** [comment]
pri zemljevidu občin se je spet pojavil problem; ko izrišem zemljevid.obsojeni se mi ta namreč izriše narobe, recimo občina Črnomelj je obarvana sivo, čeprav podatki so, občina Preddvor pa se obarva, čeprav je pri podatkih NA. 
vendar pa mini uspelo ugotoviti kje je problem, saj so podatki v tabeli, ki jo naredim z left_join še pravilni.

del kode, kjer se pojavi problem:

#uvozimo zemljevid slovenskih občin
obcine <- uvozi.zemljevid("http://baza.fmf.uni-lj.si/OB.zip",
                          "OB/OB", encoding = "Windows-1250") %>% pretvori.zemljevid()
obcine$OB_UIME <- as.character(obcine$OB_UIME)

#zemljevid stopnje obsojenih
zemljevid.obsojeni <- ggplot() +
  geom_polygon(data = left_join(obcine, obsojeni_po_obcinah2 %>% filter(leto == "2016"), by = c("OB_UIME" = "obcina")),
               aes(x = long, y = lat, group = group, fill = obsojeni), color = "black")+
  scale_fill_gradient2(low = "blanchedalmond", mid = "lightpink3",
                       high = "violetred", midpoint = 6) + 
  xlab("") + ylab("") + ggtitle("Stopnja obsojenih po slovenskih obcinah")

#obsojeni_po_obcinah2 %>% filter(leto == "2016") %>% right_join(obcine, by = c("obcina" = "OB_UIME"))

print(zemljevid.obsojeni)

#ob <- unique(obcine$OB_UIME)
#OB <- unique(obsojeni_po_obcinah2$obcina) #podatki za 212 občin
