### ISSUE TITLE
poročilo

### ISSUE THREAD

**Issue by katarinabrilej** [katarinabrilej/APPR-2017-18#5]
Pozdravljeni,

na začetku poročila sem želala pri opisu tabel dodati še vrhnji del tabele, ki se sicer izpiše, vendar pa izginejo vsi šumniki. Je mogoče kje potrebno nastaviti kodiranje, da bo delovalo?

**Comment by jaanos** [comment]
Nisem nič našel, da bi se dalo še kaj nastaviti. Pri meni sicer deluje, tako da morda lahko pustiš tako, kot je.

Sicer pa, če prav razumem, šumniki preprosto izginejo, ali se prikaže kaj drugega? Ali se isto zgodi, če poročilo prevedeš v HTML (začasno odstrani vrstico `runtime: shiny` iz glave, nato pa po prevajanju odgovori, da ne želiš pognati kot Shiny - potem seveda Shiny ne bo deloval)?

**Comment by katarinabrilej** [comment]
Bom potem pustila kar tako.
Ja, šumniki kar izginejo (namesto moški piše moki). Tudi če odstranim runtime:shiny se šumniki še vedno ne prikažejo.
